server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # WASM нужен правильный Content-Type
    types {
        application/wasm wasm;
    }
    include /etc/nginx/mime.types;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # CORS для метрик (фронт дёргает сервер напрямую)
    add_header Access-Control-Allow-Origin *;
}
