services:

  - type: web
    name: govno-orchestrator
    runtime: docker
    dockerfilePath: ./Dockerfile.orchestrator
    dockerContext: .
    plan: free
    envVars:
      - key: GOVNO_TOKEN
        value: govnotoken
      - key: RUST_LOG
        value: info
      - key: LISTEN_ADDR
        value: 0.0.0.0:3000

  - type: web
    name: govno-worker-liquid
    runtime: docker
    dockerfilePath: ./Dockerfile.worker-liquid
    dockerContext: .
    plan: free
    envVars:
      - key: ORCHESTRATOR_URL
        value: wss://govno-orchestrator-z8a5.onrender.com/producer
      - key: RUST_LOG
        value: info

  - type: web
    name: govno-worker-solid
    runtime: docker
    dockerfilePath: ./Dockerfile.worker-solid
    dockerContext: .
    plan: free
    envVars:
      - key: ORCHESTRATOR_URL
        value: wss://govno-orchestrator-z8a5.onrender.com/producer
      - key: RUST_LOG
        value: info

  - type: web
    name: govno-worker-gas
    runtime: docker
    dockerfilePath: ./Dockerfile.worker-gas
    dockerContext: .
    plan: free
    envVars:
      - key: ORCHESTRATOR_URL
        value: wss://govno-orchestrator-z8a5.onrender.com/producer
      - key: RUST_LOG
        value: info

  - type: web
    name: govno-worker-critical
    runtime: docker
    dockerfilePath: ./Dockerfile.worker-critical
    dockerContext: .
    plan: free
    envVars:
      - key: ORCHESTRATOR_URL
        value: wss://govno-orchestrator-z8a5.onrender.com/producer
      - key: RUST_LOG
        value: info
